### ISSUE TITLE
Current Queue: Almost every artist is showing "Various artists"

### ISSUE THREAD

**Issue by ronilaukkarinen** [phanan/koel-app#11]
Scrobbling just fine, but wrong artist in Artist column ("Various artists"). In [koel](https://github.com/phanan/koel) this is fixed as well. Can't these two be in "sync" with these fixes somehow?

**Comment by phanan** [comment]
That's because the various artist feature hasn't been synchronized into Koel App yet.

**Comment by ronilaukkarinen** [comment]
Hmm, I mean it shows Various artists in the artist that are not various but a single album artist. Should it not be that way? I don't have any various artist albums and it's still showing that.
