### ISSUE TITLE
automatically fill URL

### ISSUE THREAD

**Issue by thetre97** [phanan/koel-app#13]
Is there a way I can automatically add my server address, and then run npm run release to create an install, so users only have to enter email/password?

**Comment by leotop** [comment]
Change in template or in https://github.com/phanan/koel-app/blob/master/app/components/auth/login-form.vue

**Comment by thetre97** [comment]
thanks.. :)
Also, just noticed a fork has an example - https://github.com/Beachman4/koel-app/tree/master/app/config
