### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by ronilaukkarinen** [phanan/koel-app#8]
Hello! I know this is still experimental, but I can't login at all. Filling my information, password is right, but when I press Log In, nothing happens.

OS X El Capitan 10.11.5 (15F34)

````
$ npm --version
2.11.3
````

Can't get anything relevant to show Developer Tools Console. My server is running at koel.peikko.us.

**Comment by phanan** [comment]
Nothing even in the Network tab?

**Comment by ronilaukkarinen** [comment]
Nothing relevant. 

Here's the screenshots:

![Screenshot](https://dl.dropboxusercontent.com/u/18447700/Screen%20Shot%202016-07-21%20at%2015.38.44.png "Screenshot")
![Screenshot](https://dl.dropboxusercontent.com/u/18447700/Screen%20Shot%202016-07-21%20at%2015.38.56.png "Screenshot")

**Comment by phanan** [comment]
Oh. You miss the protocol in the URL field.

**Comment by ronilaukkarinen** [comment]
Doesn't work with http:// either I'm afraid. Same thing, nothing happens when I press the button.

**Comment by ronilaukkarinen** [comment]
Sorry, was too hasty. There's a delay it seems. Thanks!
