### ISSUE TITLE
Uncaught (in promise) TypeError: this.player.setVolume is not a function

### ISSUE THREAD

**Issue by ronilaukkarinen** [phanan/koel-app#9]
After login, getting in Console:

````
playback.js:273 Uncaught (in promise) TypeError: this.player.setVolume is not a function(…)
setVolume @ playback.js:273
init @ playback.js:91
_storesShared2.default.init._this.authenticated @ app.vue:61
(anonymous function) @ shared.js:59
````

Stuck in "Just a little patience..."

**Comment by izaclorimer** [comment]
I also have this issue. I am on Windows 10, with the sever on localhost.

**Comment by phanan** [comment]
I think the culprit is here https://github.com/phanan/koel-app/blob/master/app/package.json#L32. This has been fixed in Koel itself, but not in the app, which is a bit lagging behind.

**Comment by izaclorimer** [comment]
Yes this does fix the issue. I submitted a pull request [here](https://github.com/phanan/koel-app/pull/10)

**Comment by ronilaukkarinen** [comment]
Confirmed working.
